sudo: required
services:
  - docker

before_install:
  - docker build -t lukostudy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukostudy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker-demo"
  env: "react-docker-demo-env"
  bucket_name: "elasticbeanstalk-us-east-1-892173499365"
  bucket_path: "react-docker-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"